### ISSUE TITLE
table is not overlayed by grey layer when hovering over an error message

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#112]
<img width="438" alt="screen shot 2016-08-17 at 01 13 17" src="https://cloud.githubusercontent.com/assets/9099577/17730186/7dcb4bb2-641c-11e6-8837-36595b991937.png">

It seems as if all tables are _focused_ when hovering over an error message.

**Comment by blerner** [comment]
Huh?  The gray layer still is present, when you mouseover stack frames in our stack trace.  Here's a tiny program that demonstrates the point:
```
tbl = table: x, y
  row: 1, 2
  row: 2, 3
end

tbl

fun oops(n):
  if n == 0: tbl
  else: n + oops(n - 1)
  end
end

oops(3)
```
Run it, expand the stack trace, and mouseover the trace.

**Comment by schanzer** [comment]
Ooof - sorry, total brainfart on my end.

**Comment by schanzer** [comment]
@sorawee @blerner now that the entire error window floats above the gray layer, this issue is no longer relevant. OK to close?

**Comment by blerner** [comment]
This is still an issue on the latest merge, as of 8/11/2020.

**Comment by blerner** [comment]
Let's address this in #332 #329

**Comment by asolove** [comment]
Question: what is the desired behavior here for repl output that is not text? For text output, it appears the strategy is to change the background color to gray to reduce the contrast with the darker gray text. (It appears like, but is not the actual case, that a shadow is placed over the content. Instead, it's just that the background color is changed.)

As an example of a case where this happens other than tables, here is an image that uses white and a bright color, which clearly stands out and destroys the illusion of the shadow:
<img width="912" alt="image" src="https://github.com/brownplt/code.pyret.org/assets/8495/e354c9c2-9d1d-484c-9a49-17414c8a80f8">

An imperfect, but I think better, solution, is to add a rule so that all repl output has reduced opacity in this state:
<img width="915" alt="image" src="https://github.com/brownplt/code.pyret.org/assets/8495/25c8dcd0-508f-44e9-9ef2-a3b17f2eb766">

I'll submit a PR so folks can merge that if it's an improvement.

**Comment by blerner** [comment]
I like this. Conceptually, I think of it as three z-index layers: all the program and repl content, the gray "deemphasizing" later, and the topmost error message.

**Comment by schanzer** [comment]
Whoa. This whole time I thought there was just a partially transparent masking DIV, and the problem was just janky z-indexing! That's a nice fix to a 7 year old issue!
