### ISSUE TITLE
Error rendering error on no-cases-matched

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#117]
Don't know if this is a known issue or not.

<img width="626" alt="screen shot 2016-08-23 at 08 28 49" src="https://cloud.githubusercontent.com/assets/9099577/17898218/c9c2592c-690b-11e6-85a3-4da921372099.png">

Code to reproduce:

```
[{}: ]
```

**Comment by blerner** [comment]
@jswrenn, this is probably a pyret-lang bug, right?

@sorawee for what it's worth, when defining maker objects like this, you need to define make0, make1, make2, make3, make4 and make5, in addition to make.

**Comment by jswrenn** [comment]
Yeah, a pyret-lang bug. 

The real bug here is that the desugaring is leaking because the wrong error message is being thrown; there is no user-facing 'field lookup expression'. 
> for what it's worth, when defining maker objects like this, you need to define make0, make1, make2, make3, make4 and make5, in addition to make.

This is the real bug: the thing in the maker-object position isn't of the right type. The desugaring of `s-construct` expressions should check that the expression in `constructor` position evaluates to something that is the right type.

**Comment by blerner** [comment]
@jswrenn this is related to the other non-exhaustive-match problems I'm seeing on other bugs in pyret-lang.  Now, the error message reads,
```
Evaluating the field lookup expression at interactions://1:1:1-1:3 errored.

The left side was an object that did not have a field named make0:
   {}

One or more internal errors prevented us from showing the best error message possible. Please report this as a bug.
```
with the internal error being, your error message rendering (not sure which error it is, but probably lookup-non-object), is looking for `ast.obj.l`, and there is no `obj` field on the `s-obj` ast object itself.

**Comment by blerner** [comment]
This specific error seems to be fixed now.  Dunno if we should keep this open?
