### ISSUE TITLE
Indenter is off when there is a field without a trailing comma

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#200]
```
data A:
  | a with:
    b: 2
end

fun x():
1
end
```

**Comment by blerner** [comment]
That's weird...  @belph can you take a look?

**Comment by belph** [comment]
Will do.

**Comment by belph** [comment]
This has been fixed. The problem (in case you're interested) was that the `:` was introducing a field indentation. `,` and `}` close that indentation, but `end` wasn't handling it correctly (since the dedenter for `end` needs to know to skip the `"OBJECT"` entry on the `ls.tokens` stack in that specific instance).

Regardless, it's fixed now, and I've added a regression for it to the pyret-codemirror-mode `index.html` file.
