### ISSUE TITLE
Include seen to not work, and screw up identification of REPL entries

### ISSUE THREAD

**Issue by blerner** [brownplt/code.pyret.org#219]
On current pyret-horizon.herokuapp:
![image](https://user-images.githubusercontent.com/918464/29490412-df1d1842-8508-11e7-89dd-df8b8ebb398b.png)

**Comment by jpolitz** [comment]
Closing; seems to be fixed:

![image](https://user-images.githubusercontent.com/119891/29677014-97f98942-88ae-11e7-8b33-8ed258cc6a89.png)

**Comment by jswrenn** [comment]
Not so fast, @jpolitz. The last major commits to either pyret-lang or code.pyret.org were seven days ago; this issue was filed five days ago.

I'm not sure that this is _just_ a highlighting issue, too. The types of errors @blerner and you encountered are completely different (`unbound-id` and `arity-mismatch`, respectively).

There _is_ still a strictly highlighting issue in your screenshot @jpolitz. I can't replicate @blerner's error, so I'll tackle the issue of "operator" having too-wide of a highlight.

**Comment by jpolitz** [comment]
Can we make the issue more specific? The original screenshot isn't causing an error any more, and "bad highlights" can refer to a zillion different things.

**Comment by blerner** [comment]
My hunch is there are two problems that caused my original issue, but I can't track either of them down. One is, sometimes hitting the run button or pressing enter in the repl doesn't "take", and there's some kind of race between when the buttons get activated and when Pyret really starts running. The other is sometimes the error message highlights on repl entries get confused which entry to point to. I've seen both things happen, and collectively that explains my original screenshot: the include didn't work, and the highlight went to the wrong entry.

**Comment by sorawee** [comment]
I confirm what Ben said about "race between when the buttons get activated and when Pyret really starts running". Pretty much, we need to wait until "REPL is ready" appears in the js console before hitting run or using REPL. Otherwise, it results in a silent error. I encounter this bug every time I do plot library development that I get used to it, but it would be pretty rare for most users since no one is going to use the REPL or hit the run button that fast.

**Comment by blerner** [comment]
Is this still a race condition, or have we fixed this sometime in the past year?

**Comment by schanzer** [comment]
@blerner @sorawee poking to see if this is still an issue

**Comment by schanzer** [comment]
@blerner OK to close?

**Comment by sorawee** [comment]
As far as I can tell, the race condition problem is gone. The Run button is only clickable after "REPL is ready" appears. Similarly, the REPL is blocked by the rotating lambda until "REPL is ready" appears.

**Comment by schanzer** [comment]
@blerner poke?

**Comment by schanzer** [comment]
@blerner ok to close?
