### ISSUE TITLE
stop-when w/last-picture handler

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#25]
This was recently added to the jsworld implementation that whalesong uses (https://github.com/soegaard/whalesong/commit/0064ec20c393653a6a7c3d89d30f01ce4f615928), which is virtually identical to Pyret's. This functionality is one of Bootstrap's most highly-requested features, which was recently added to WeScheme.

**Comment by schanzer** [comment]
Poking since this will likely become a higher priority as spyret progresses...

**Comment by jpolitz** [comment]
Can you say a sentence about spec for this, like where this last-picture gets rendered?  Does it just stay up in the big-bang window, or does it get shown at the REPL or somewhere else?

@sorawee added `close-when-stop`, which controls whether or not the big-bang window stays _open_ on a stop-when, and it stays open on the first frame for which `stop-when` returned false.  Is that accomplishing the same thing?

For example, if I do:

```
big-bang(0, [list: on-tick(lam(w): w + 1 end), to-draw(lam(w): text(tostring(w), 24, "black") end), stop-when(lam(w): w > 15 end)])
```

The final frame shows `16`, not `15`.  Is this the goal?

**Comment by schanzer** [comment]
See http://docs.racket-lang.org/teachpack/2htdpuniverse.html#%28form._world._%28%28lib._2htdp%2Funiverse..rkt%29._stop-when%29%29

**Comment by jpolitz** [comment]
Got it.  That's really nice, actually.  It maintains the invariant that to-draw is only called with worlds for which stop-when returns true.  This is straightforward to add.

**Comment by sorawee** [comment]
Just curious: can't normal big-bang do this already, using a combination of `on-tick`, `stop-when`, and `to-draw`? This is basically what I did for Rocket (CS19 assignment) to get the same functionality as this `last-picture`.

**Comment by jpolitz** [comment]
@sorawee yes, this doesn't add new expressiveness. However, it's useful that last-picture doesn't need to be the same as what to-draw would generate, so the to-draw function can be written to only consider the non-stopping range of values.

**Comment by shriram** [comment]
@sorawee I had this added to Racket because in its absence, you have to engage in a complex encoding that is inaccessible to most beginners. (For instance, sometimes you have to augment your notion of state — your world becomes a conditional of "game in progress" vs "game over".  Not only does _every single handler_ then has to have a `cases`, worst of all, most handlers will _never see_ the "game over" state: so the only thing they can say in that branch of the `cases` is "should not get here and if I do, I have no idea what to do".)

Since it's very natural for students to want to put up a splash screen when their game finishes (you won! you lost! your score is …!), this is a key feature to make nicer-feeling games accessible.

**Comment by blerner** [comment]
Dupe of https://github.com/brownplt/pyret-lang/issues/808?

**Comment by shriram** [comment]
@blerner Not quite. The main thrust of that report is the semantics of when the handlers are called; `last-picture` is a bit of a side-track from that:
https://github.com/brownplt/pyret-lang/issues/808#issuecomment-236464115
The main thrust of this is to add a `last-picture` feature at all.

**Comment by schanzer** [comment]
There's a PR for this at #218

**Comment by schanzer** [comment]
`big-bang` has been deprecated, no? If so, let's close this. If not, what else needs to be done with the PR?

**Comment by schanzer** [comment]
@shriram I can confirm that this is implemented (and then some!) in reactors. Closing, but feel free to reopen if you disagree
