### ISSUE TITLE
Awkward filename display

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#251]
![screenshot from 2017-11-14 23-20-13](https://user-images.githubusercontent.com/9099577/32818651-81adc07a-c992-11e7-8bf8-b8f05df7cff1.png)

The full filename is in fact `interp-lazy-code.arr`.

Suggestion:

```
fun get-new-name(s :: String) -> String:
  if string-length(s) >= 24:
    replace-so-that-the-length-is-exactly-23(s)
  else:
    s
  end
end
  
```

**Comment by shriram** [comment]
No, don't change the length cutoff! Just be smarter about truncation. Don't use “…” unless you're _actually_ eliding something.

**Comment by blerner** [comment]
You're quibbling about wording but saying almost the same thing.  Oak, you're wrong in the specific details of "3 characters" here, though: the dots are a single-character ellipsis, so literally, the entire fix is to change https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/beforePyret.js#L307 to use `<=` instead of `<`

**Comment by blerner** [comment]
(Basic arithmetic is hard early in the morning...)
