### ISSUE TITLE
Testing and indentation

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#252]
I think the sensible indentation here is like this:

```
check:
  some-function-call(some-parameter)
    is [list:
      [list: 1, 2, 3, 4],
      [list: 1, 2, 3],
    ]
end
```

Or:

```
check:
  some-function-call(some-parameter)
    satisfies lam(v):
      blah
    end
end
```

But currently it's like this:

```
check:
  some-function-call(some-parameter)
    is [list:
    [list: 1, 2, 3, 4],
    [list: 1, 2, 3],
  ]
end

check:
  some-function-call(some-parameter)
    satisfies lam(v):
    blah
  end
end
```

**Comment by blerner** [comment]
Closing as wont-fix: this isn't technically feasible with the indenter (because it requires a full parse to figure out where the end of the expression is, which is information we do not have), and it violates the current uniformity principle, that if you add newlines within a multi-line expression, later lines don't need to reindent.
