### ISSUE TITLE
Feature request: bracket highlight inside quotes

### ISSUE THREAD

**Issue by sorawee** [brownplt/code.pyret.org#253]
I notice that a lot of students are frustrated that there is no easy way to see paren mismatch inside quotes in CPO. Something like:

```
eval('(let (f (lam x ((x 1) (x 2)))) (let (g 2) (f (f g)))')
```

One workaround that they attempt was to remove the quotes so that Pyret can highlight, but `lam` is expected to match with `end`, so it unmatches the right paren and messes everything up. That is, this workaround doesn't really work. Usually they end up copying the code into another text editor like Atom to fix the unmatched paren and copy back. I think this is a bad user experience.

It would be nice to have something like https://codemirror.net/demo/sublime.html which supports highlighting inside quotes.

Notice that there are two contexts: inside quote and outside quote, and in each context there is a separate paren matcher. That is:

```
"(")
```

are not considered matched.

I think the current styling for the context outside quotes are great already. However, inside quotes unmatched or wrong matched paren could happen naturally. I.e.:

```
if x == ')': # unmatched
  ...
else if x == '(' # unmatched
  ...
else:
  ...
end
```

or

```
if x == '(':
  ... # this line should not be highlighted
else if x == ')'
  ...
else:
  ...
end
```

So we might need another style for the inside quote context. In particular, it should only highlight the parens and not the content in between.

**Comment by belph** [comment]
I'm totally fine with this, but I'm mostly curious: why do so many students want this? I see little reason for wanting matches highlighted inside of strings...

But again, I'm happy to add it. @blerner may want to weigh in on the styling.

**Comment by blerner** [comment]
I tend to detest paren-matching inside quotes, because typical implementations I see of it will continue their matching across different strings, like this: `"(" + ")"` shows two pairs of matched quotes and one pair of matched parens.  Both options of highlighting there are annoying: showing them as matched means you have a global matching problem that more often than not gets screwed up by the order you happen to write programs in; showing them as unmatched just means Pyret will visually yell at you every time your cursor moves over those strings.

The specific example you're showing above, of writing an interpreter for an s-expression-based language as a string-literal within Pyret, seems sufficiently over-specific that I don't really want to change Pyret/CPO's behavior here.

**Comment by shriram** [comment]
This has bugged me, too, for a long time.

@belph as Ben intuits, this is really useful when writing code inside strings, which happens all the time when writing interpreters.

If we think this is "sufficiently over-specific" so as to not be handled, that makes Pyret an inappropriate choice for a book like PAPL, which is about 25% of its use-cases…

**Comment by blerner** [comment]
I wouldn't go quite that far, Shriram.  Text is text; I don't think an IDE for plain text ought to show internal structure on it.  But there are other kinds of strings -- think of languages with `#{interpolated}` contents, like JS or ruby -- and those might be deserving of a different delimiter and different support...

**Comment by belph** [comment]
Maybe the solution is to show matching parentheses in a single string and _not_ show the scary highlighting for unmatched parentheses (or maybe _less_-scary-yet-still-scary highlighting)?

**Comment by sorawee** [comment]
A few thoughts:

1. I think the reason it allows bracket matching across strings is that one could have this code

    ```
    x = "(+ 1 2 " + cat + " (3 4 5) " + dog + " )"
    ```

    If we have something like `format("(+ 1 2 \1 (3 4 5) \2 )" , [list: cat, dog])` or `[sprintf: "(+ 1 2 \1 (3 4 5) \2 )" , cat, dog]`, limiting to one string might work.

2. Totally crazy idea: some languages have prefix before string literal, like `r"1\n2"` vs `"1\n2"` in Python. JavaScript also has one. Perhaps bracket matching only happens inside `s"..."` or something like that?

**Comment by blerner** [comment]
Those were exactly my points, Oak. I *hate* it when parens are matched across multiple strings, because it inevitably occurs that one parenthesis or another is unmatched (eg in a key handler) and then parenthesis matching is forever screwed up for the rest of the file. That happens to me far, far more often than writing a balanced s-expression...

Having a marker for "strings that are worth balancing parens inside" might be worth it. Maybe.

**Comment by shriram** [comment]
I fully agree with Ben that matching parens *across* strings really sucks.
Sometimes it's the right thing and then it's awesome, but when it's the
wrong thing (which it also sometimes is), it screws up the entire program
for the rest of time.

**Comment by blerner** [comment]
Closing as #wontfix
