### ISSUE TITLE
can't get the editor to work

### ISSUE THREAD

**Issue by abuakram** [brownplt/code.pyret.org#294]
trying since days but failed to get passed the installation process:
WHAT AM I DOING WRONG? 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'local-install' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prelocal-install', 'local-install', 'postlocal-install' ]
5 info lifecycle code.pyret.org@0.0.0~prelocal-install: code.pyret.org@0.0.0
6 info lifecycle code.pyret.org@0.0.0~local-install: code.pyret.org@0.0.0
7 verbose lifecycle code.pyret.org@0.0.0~local-install: unsafe-perm in lifecycle true
8 verbose lifecycle code.pyret.org@0.0.0~local-install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/******/code.pyret.org/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle code.pyret.org@0.0.0~local-install: CWD: /home/******/code.pyret.org
10 silly lifecycle code.pyret.org@0.0.0~local-install: Args: [ '-c', 'heroku local:run npm install' ]
11 silly lifecycle code.pyret.org@0.0.0~local-install: Returned: code: 1  signal: null
12 info lifecycle code.pyret.org@0.0.0~local-install: Failed to exec local-install script
13 verbose stack Error: code.pyret.org@0.0.0 local-install: `heroku local:run npm install`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid code.pyret.org@0.0.0
15 verbose cwd /home/******/code.pyret.org
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "local-install"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error code.pyret.org@0.0.0 local-install: `heroku local:run npm install`
22 error Exit status 1
23 error Failed at the code.pyret.org@0.0.0 local-install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jpolitz** [comment]
Hi there, thanks for reporting this. A few comments/questions:

It looks like this is the output of running `npm run local-install`, just so I'm clear where I think you are in this. If that's not true, I'd really like to see the command you're running. Since the `heroku local:run ...` command is failing, my first guess would be to check if the `heroku` command is installed and in your path.

If I remove my install of `heroku`, I don't get exactly this error, so I'm not positive that's the case.

Beyond this command, what other configuration (e.g. edits to `.env`), setup, or commands have you done in the checkout you're working in? The thing that might be most helpful is a transcript of the commands you've run on a fresh checkout of the repository that lead to this error.

Overall, what are your goals for building? Do you want to make your own improvements to code.pyret.org? Knowing what you want to do could help give more targeted feedback for what parts of the system you need to worry about or configure.

**Comment by jpolitz** [comment]
Also, to be clear for anyone visiting this issue just looking to program in Pyret, you can always just visit code.pyret.org and program from there. This issue is related to building and doing development to add features to Pyret and its IDE, which isn't something most students or instructors will ever need to do.

**Comment by abuakram** [comment]
Thanks @jpolitz for your reply...

1) I want to try out pyret since I'm interested in Htdp. I have tried the online version, but the left side of the editor in which you write your code won't work on my side... I don't know where the problem could be... I am running ubuntu 18.04 and firefox as my browser...

2) So I am trying to code offline and found this option... (Are there other options, like for example a teachpack for drracket?)...

- I installed Heroku in my home folder
- logged in
- downloaded zip file from this repository and extracted it
- cd into code.pyret.org
- sudo npm run local-install 

these were my steps 

Hope for an advice, or for other options

Thanks

**Comment by abuakram** [comment]
sorry, forgot ... I am following the steps mentioned in this page... so I mv .env.example to .env without changing anything

**Comment by jpolitz** [comment]
Thanks for the response! I'd like to know more about how code.pyret.org online isn't working for you, because that would definitely be the easiest way for you to do HtDP-style programming.

First, can you tell me a little more about what it looks like when the left side doesn't work? A few specific questions that may help us diagnose the issue:

- Can you not type, as in the definitions part on the left is un-editable?
- Are there any error messages onscreen?
- Does the Run button do anything when you click it?

Also, if you could tell us the version of Firefox you're using, that would be really helpful as well.

Another option is to try Chromium or Brave to load once, not as a permanent solution (you shouldn't need to change your browser for this), but it would help isolate if Firefox is the issue.

Thanks for reaching out, and sorry you ran into issues with this!

**Comment by abuakram** [comment]
I am using latest version of firefox...
I indeed tried the online editor on a different browser, but didn't work too...
![screenshot](https://user-images.githubusercontent.com/9851450/46096826-796f0280-c1c0-11e8-8391-4b2ae783864d.png)
See? Can't write on the left side, and no error messages.. Coding and running on the left side is working... no issue here.

**Comment by jpolitz** [comment]
Hi @abuakram I want to get a clarification on your last few comment.s Are you saying there's no issue at all? No issue in Chromium? Or just that the right side is editable and runnable and the left side still is not, across both browsers you tried?

Thanks!

**Comment by jpolitz** [comment]
Got it. Do you have any content/ad blocker-like extensions installed in those browsers, or are you on a network that might be blocking content? In general, do you do anything to block Google-related domains?

I checked out your screenshot in more detail, and it looks like some Google Drive-related libraries might not be loading. I can think of ways where those not loading could cause the definitions window to not become active. I'd like to fix it, since they shouldn't be required to even load if you don't want to save code to Drive. I need a little more information to track down why that could be.

Thanks for following up!

**Comment by abuakram** [comment]
- Yes ... I am using an Ad-Blocker in my browser...
- My network doesn't block google related material... but google does. Some sites belonging to google are not accessible.

I assume this could be the matter... 

I tried: proxychains npm run install-local ... but npm refuses running through a proxy

**Comment by abuakram** [comment]
Just tried:
 sudo proxychains npm run local-install 

and got following log file```


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'local-install' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prelocal-install', 'local-install', 'postlocal-install' ]
5 info lifecycle code.pyret.org@0.0.0~prelocal-install: code.pyret.org@0.0.0
6 info lifecycle code.pyret.org@0.0.0~local-install: code.pyret.org@0.0.0
7 verbose lifecycle code.pyret.org@0.0.0~local-install: unsafe-perm in lifecycle true
8 verbose lifecycle code.pyret.org@0.0.0~local-install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/abuakram/Apps/code.pyret.org/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle code.pyret.org@0.0.0~local-install: CWD: /home/abuakram/Apps/code.pyret.org
10 silly lifecycle code.pyret.org@0.0.0~local-install: Args: [ '-c', 'heroku local:run npm install' ]
11 silly lifecycle code.pyret.org@0.0.0~local-install: Returned: code: 134  signal: null
12 info lifecycle code.pyret.org@0.0.0~local-install: Failed to exec local-install script
13 verbose stack Error: code.pyret.org@0.0.0 local-install: `heroku local:run npm install`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid code.pyret.org@0.0.0
15 verbose cwd /home/abuakram/Apps/code.pyret.org
16 verbose Linux 4.15.0-34-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "local-install"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 134
22 error code.pyret.org@0.0.0 local-install: `heroku local:run npm install`
22 error Exit status 134
23 error Failed at the code.pyret.org@0.0.0 local-install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by abuakram** [comment]
I'm so sorry to bother you so much... but their ain't much help online...
I read somewhere that pyret can be codded in DrRacket... Is that true?

**Comment by schanzer** [comment]
This issue is two years old. Still unresolved?
