### ISSUE TITLE
Request: New chart type

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#311]
There's a strong pedagogical win if we can provide a version of `scatter-plot` that also consumes a function of type `Row -> Image`, and uses the generated image in places of the dots in the plot.

**Comment by blerner** [comment]
Would we rather encourage students to `extend` their tables (or use `build-column`), and then have a version of the scatter-plot function that simply takes in a third column to use for images?  (Thereby reinforcing existing table mechanisms that we're already teaching, and avoiding a higher-order function that we might not be teaching?)

**Comment by schanzer** [comment]
Ooooh, I love that. Even better!

**Comment by shriram** [comment]
Also it's a great suggestion because they can much more easily debug their
output. It's like creating an intermediate variable, except one that's
completely manifest in the table itself. They can scroll through several
rows to make sure they're getting the right image, etc. It fits quite
nicely with our testing story: on your "testing" table, scroll and make
sure you have the right outputs, only then send this off to work on the
"big" table.

**Comment by jpolitz** [comment]
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/119891/89936808-0a8acf00-dbc9-11ea-8ab1-c5badb64034e.png">
