### ISSUE TITLE
Styles disappear due to cross-tab interactions.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/code.pyret.org#345]
1. In tab A, open https://code.pyret.org/editor
2. In tab B, open https://code.pyret.org/editor#share=1ygUsAC-SLh6-nc-Hqp0cdLkvJiwxyRuV&v=8973759
3. Close tab B.
4. Switch to tab A.

Result:
![screenshot-code pyret org-2020 09 08-13_44_23](https://user-images.githubusercontent.com/3820879/92510179-7026a700-f1d9-11ea-8890-e722c11140b2.png)

**Comment by thomascastleman** [comment]
It appears the `body`'s class is getting replaced completely (and therefore dropping the theme class which tells it where to get the colors from).

When I inspect I get `<body class="1gx416c1bl2ftv1i9i8z592bi8ruzoo9n6zr0ip">` after the interaction. Do you know where this new class is coming from? If we can get it to just add the class instead of removing the previous that may be all we need to do.

**Comment by jswrenn** [comment]
It seems to be coming from `applyTheme`.

If you right click the `<body>` element in Chrome's Inspector, you can set a js breakpoint on attribute modification.

**Comment by jpolitz** [comment]
Shouldn't there be a guard on this code to only call `f` if `e.key` is equal to the provided key?

https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/localSettings.js#L25

**Comment by jpolitz** [comment]
(@thomascastleman I wouldn't assume that class is supposed to be added to `body` at all)

**Comment by jpolitz** [comment]
I think this is fixed/deployed now, could someone else check the repro @jswrenn gives above to confirm?

**Comment by thomascastleman** [comment]
@jpolitz It appears to work now! Thanks
