### ISSUE TITLE
Code containing extended-ASCII characters is not supported

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#38]
(define ü 42) doesn't work, and I can guarantee you that you'll get some requests for it. Was this an explicit design decision?

**Comment by jpolitz** [comment]
That's a Scheme program, so if we're talking Spyret I'm not sure why the parser would behave differently between WeScheme and Pyret.  @ds26gte, any idea where the failure is happening?

From Pyret's point of view, I'm not thrilled with needing to answer questions like: how many variables are defined by this program?

```
(define ü 42)
(define ü 42)
```

How are they different?  One is a u followed by a combining diaeresis, and the other is "latin small letter u with diaeresis," which are different (sequences of) code points.  I can generate the latter by typing "Option-u u" on OSX, and the former by entering "u\u0308" in the JS console and copy/pasting it.  See:

http://www.wescheme.org/view?publicId=AMphdBqBWm

I'm not sure what other input formats would generate, but this requires some careful design to not end up with really bizarre corner cases (and with a sufficiently complex parser, this can even turn into a security issue).  Racket does carefully define these for its syntax, so this is certainly doable, but I'm not sure the same answer is right for Pyret, or that we want to take on that complexity in the context of JavaScript's bizarre unicode encoding scheme and the fact that parsing is a hard enough problem already relative to error messages, etc.

This example is sort of the tip of the iceberg.  ASCII is a wonderful simplifying design decision.  And as long as we support unicode in _strings_, the tricky unicode questions are limited to the string operations, rather than being fundamental to the language's syntax.

**Comment by ds26gte** [comment]
Emu's Spyret program is simply inheriting the identifier ("name") constraints of Pyret. There may already be well-defined "letter" subsets of Unicode that can be a plug-in substitute for the character subpattern A-Za-z in the token regexp for Pyret names. This should bless U+00FC (single character ü) but not u followed by U+0308.  

Expanding Pyret's notion of "letter" in this way is simple but also conservative and doesn't really rock the boat. For:

1. It avoids your example of having two identifiers looking the same (which Racket has), because only one of them is valid. (The current policy avoids the example by invalidating both.)

2. Racket allows non-"letters" too (both Unicode and plain ASCII), because it lets in characters like ≤ and ≥, whereas Pyret doesn't countenance even ASCII < and > in its names. With the above régime, the guiding constraint that Pyret names should only have letters, underscore, digits (but not as prefix), and hyphens (but not as suffix) remains in place. 

--dörai

**Comment by ds26gte** [comment]
spyret.herokuapp.com and cpyret.herokuapp.com currently allow identifiers to contain letters from an extended Latin set. Details in lines 116+ of https://github.com/ds26gte/pyret-lang/blob/horizon/src/js/base/pyret-tokenizer.js.

Roughly, these are the letters used in the headwords (not phonetic transcription or etymological annotation) in the two big-name unabridged English dictionaries. This should cover all the letters used by any contemporary natural language that uses the Latin alphabet (as English has poached words from all of them).

**Comment by blerner** [comment]
N.B., you'll need to update the pyret.js mode of CPO, and change how
    it recognizes identifiers there, too.
    
    On 9/25/2015 3:39 PM, ds26gte wrote:
    
    
      spyret.herokuapp.com and cpyret.herokuapp.com currently allow
        identifiers to contain letters from an extended Latin set.
        Details in lines 116+ of https://github.com/ds26gte/pyret-lang/blob/horizon/src/js/base/pyret-tokenizer.js.
      Roughly, these are the letters used in the headwords (not
        phonetic transcription or etymological annotation) in the two
        big-name unabridged English dictionaries. This should cover all
        the letters used by any contemporary natural language that uses
        the Latin alphabet (as English has poached words from all of
        them).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jpolitz** [comment]
I'm confused about why Pyret's tokenizer needs to be involved here.  Isn't Spyret creating a Pyret AST directly from the Scheme parser data structure?  Why is Pyret's grammar involved at all?

**Comment by blerner** [comment]
...because I thought you were still using the Pyret CM mode.  Nevermind; you obviously have the existing Scheme-y CM mode, and this last comment is irrelevant.

**Comment by jpolitz** [comment]
My question was directed at @ds26gte, actually – I don't understand why Pyret's tokenizing is involved in Spyret.

**Comment by ds26gte** [comment]
I'm experimenting with the WeScheme -> Pyret AST presently. Currently (as said in my original email, so folks will have something to work with), it is using the inefficient WeScheme -> Pyret AST -> Pyret -> Pyret AST.

**Comment by jpolitz** [comment]
Duh, I'm sorry, forgot. That makes total sense.

**Comment by schanzer** [comment]
@ds26gte , this appears to be working well in Spyret now. Are there still subtleties you're tracking, or should I close this out?

**Comment by ds26gte** [comment]
You can close it out unless there is a design opinion that we should disable non-ASCII Unicode characters from being used.
