### ISSUE TITLE
resize with Bonnie menu open causes editor to start halfway down screen

### ISSUE THREAD

**Issue by thomascastleman** [brownplt/code.pyret.org#384]
To reproduce:

1. Open the Bonnie menu
2. Click and drag the middle bar between definitions/interactions windows to resize

The top of the editor and REPL are now positioned just below where the Bonnie menu ends. Resizing again with the menu closed causes them to return to normal.

**Comment by asolove** [comment]
The same thing also happens if you replace step 2 with resizing the whole browser window.

The issue here is that `updateEditorHeight` in `beforePyret.js` sets the height of the editor and REPL by subtracting the height of the toolbar. But the Pyret menu is positioned such that it makes the toolbar taller when it appears. We need to change either the JS calculation or the CSS for the menu so that the toolbar height isn't changed by the menu.

**Comment by asolove** [comment]
I think this can be closed now.
