### ISSUE TITLE
pyret thumbnails of box-plots accidentally emphasize some lines over others

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#401]
From [an issue @flannery-denny originally posted in the curriculum repo](https://github.com/bootstrapworld/curriculum/issues/577), which I suspect is a scaling algorithm issue:

> See [this file](https://code.pyret.org/editor#share=1q_yHgXVUHMeqVfdEuWotGXy4k149ecqZ&v=1904b2c)
> with this code `box-plot(table, "a")`
> screenshots below
> 
> ![Screen Shot 2021-08-27 at 8 19 02 AM](https://user-images.githubusercontent.com/66691020/131133978-ff87f4a4-09e1-402f-9610-a2e6d75d8508.png)
> ![Screen Shot 2021-08-27 at 8 19 09 AM](https://user-images.githubusercontent.com/66691020/131133982-64c09974-b21d-4f3c-a275-e2ce2409cf53.png)
> ![Screen Shot 2021-08-27 at 8 23 44 AM](https://user-images.githubusercontent.com/66691020/131134251-5e0b1bdc-dc37-4c56-9c45-a5d75e4e3457.png)

My hunch is that one of the vertical lines, when scaled, is falling on a pixel boundary. As a result, we get two pixels of gray instead of one pixel of black. This has the result of making it appear that one vertical line is "emphasized" over the others. I wonder if toggling [`imageSmoothingEnabled`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled) would make a difference?

**Comment by blerner** [comment]
This doesn't replicate on my laptop, in either Chrome or Firefox (the plots are columns `a`, `b`, `c` and `d` in order):
![image](https://github.com/brownplt/code.pyret.org/assets/918464/d98cff3c-b6f8-4124-a1d0-3d4ac209e383)

It's worth pointing out that your suggested fix of setting `imageSmoothingEnabled` is moot, since the _default value is already true` as pointed out by that very doc link!

I'm not sure how you're seeing what you're seeing, but I suspect it's very much laptop-and-OS-dependent, and therefore not readily fixable.  Worth closing?

**Comment by schanzer** [comment]
@blerner yeah, let's close
