### ISSUE TITLE
Expose the color-generator from error messages

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#422]
We'd like to be able to get a stream of colors (as many as we need!), for use in the chart library via `.colors(..)`.

(related to #412)

**Comment by blerner** [comment]
Aesthetically I don't think you quite want to use those, because honestly a bunch of the colors tend towards the olive-greeny-orange chunk of the color wheel... Also, even though pairwise any two consecutively generated colors have sufficient contrast, colors that are two apart do not tend to look as good together.  (The gist of it is that each pair of colors is roughly 6/11s of the way around the circle, which gives a lot of contrast, but then colors 1 and 3 are only 1/11 apart.  I'm simplifying away `phi / pi` irrational fractions, but that's the upshot.)

You likely want to use a different coloring generation scheme that generates a wider variety of colors (shades/tints, as well as hues).  I attempted something like this at https://pyret.slack.com/archives/C1E30822E/p1639246388000200, for what it's worth...

**Comment by schanzer** [comment]
Cool! This will take me some time to port over to CPO, but it's helpful to have a good place to start.

On the flip side - is this the kind of thing we'd want to expose from within CPO itself? Assuming the answer is no, but wanted to check since it's possible that other libraries might want something like this.

**Comment by blerner** [comment]
No.  I think this may be the sort of thing we'd like to have as a community-supplied library, but I don't think we need it to ever be "baked in" to CPO.

**Comment by schanzer** [comment]
[2d color palette.txt](https://github.com/brownplt/code.pyret.org/files/8043871/2d.color.palette.txt)

Adding your CPP file here for posterity. I've got some work ahead of me. :)

**Comment by blerner** [comment]
not c++!  it's TypeScript

**Comment by schanzer** [comment]
That's odd - when I downloaded the file it had a `.cpp` extension...

**Comment by schanzer** [comment]
@blerner our need for this is long gone, and we're the only ones who ever asked for it. OK to close?
