### ISSUE TITLE
Display of non-ASCII characters in strings

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#47]
(Extension of a conversation we've had in other contexts)

How should the string "ä" display as REPL output? There's an argument for showing the unicode value, or the character itself. IIRC, we'd decided that this would be handled much in the same way we handle rationals: toggle between both forms onclick().

**Comment by schanzer** [comment]
The relevant WeScheme code for this is https://github.com/bootstrapworld/wescheme2012/commit/87beee1c52114e2871cfb152ecd257460c2cad65

**Comment by blerner** [comment]
This is a fairly easy bug to fix in CPO, too -- Basically, adapt the `textToDomNode` code that @schanzer linked to above, and insert it into https://github.com/brownplt/code.pyret.org/blob/master/src/web/js/output-ui.js#L581 in lieu of the simple-minded code that's already there.  You can use the code above it (https://github.com/brownplt/code.pyret.org/blob/master/src/web/js/output-ui.js#L540) that deals with toggleable fraction displays as a model.

Any takers? :)

**Comment by blerner** [comment]
https://github.com/brownplt/code.pyret.org/commit/5aa7e1d2ba56cf6472efb04057ea18df72c74a36 gives an initial implementation, but some refining might be warranted.

**Comment by blerner** [comment]
@schanzer: poke around on this, and see how well/if you like it.  I didn't reuse the WeScheme code here, because our DOM stuff was sufficiently different that it wasn't worth the time to figure out how yours worked, which means I don't quite know if I replicated the behaviors the same.  Off-github, I've emailed Shriram trying to brainstorm how to render mutli-line strings (should we show the escape sequence, or the newline) while making things still be copy-pasteable.  Not quite an easy UI choice.  Any thoughts?

**Comment by schanzer** [comment]
This looks awesome. Close as horizon-fixed?

**Comment by blerner** [comment]
Not yet; I think @shriram wants a bit more than this.

**Comment by schanzer** [comment]
@shriram can you weigh in on this? This works exactly as I'd imagine.

**Comment by schanzer** [comment]
Pinging @shriram.

**Comment by shriram** [comment]
On pyrroneous, this now looks good. Hopefully it does so on other branches as well…
