### ISSUE TITLE
Common Error needs better message

### ISSUE THREAD

**Issue by schanzer** [brownplt/code.pyret.org#56]
data Foo:
  | foo(x:: Number) 
end

fooA = foo(42)
\# student tries to get x out of fooA...
Foo.x

Another common error uses the lowercase foo as the object. These errors happen a *lot* in BS:2. Having a really good error message for them would be awesome.

**Comment by blerner** [comment]
Are you worried about the `foo.x` and `Foo.x`, or the missing `end` because of the extraneous `let`?

**Comment by schanzer** [comment]
Sorry, I was writing that out in a hurry. Edited to be sensical.

**Comment by blerner** [comment]
Ok.  I think this is feasible in the special case above, of constructors and type-predicates that were defined by `data`.  It'll require some runtime support, but it should be possible.  Do you have a suggested wording for what you want to see, or just "anything but _that_..."?

**Comment by schanzer** [comment]
I need to spend more time in Pyret looking at other error messages (and I'm sure the space of what's possible will change with @jswrenn 's additions!), but what comes to mind is something like...

"Tried to look up field x inside of type Foo, but field lookups can only be performed on objects."
"Tried to look up field x inside of function foo, but field lookups can only be performed on objects."

**Comment by sorawee** [comment]
Does Bootstrap use the term "constructor"? And does Pyret keep the information around that `foo` is a constructor? If both of these are true, then using "constructor" instead of "function" would even be more precise / understandable.

**Comment by schanzer** [comment]
Yeah, we use the term 'constructor' - and 'accessor' too, FWIW.

**Comment by blerner** [comment]
@schanzer FYI, `Foo` in your example is _not_ a type; it's actually a _boolean function_ that returns true on those Pyret values that are Foo's.

@jpolitz looking at this some more, I don't much like the technical means necessary to implement it.  I can hack in a reflective field on constructor functions, so that we can recognize things like `foo` within `getFieldLocInternal` and throw a different error in that case.  Something like: "The field lookup expression <foo.x> attempted to lookup a field on a constructor for `foo`, rather than a constructed `foo` object."

But how do we handle `Foo`?  Or, for that matter, any other functions?

It also makes constructors a bit weird(er), in that they really are functions, but they start to behave unlike functions in error contexts...

**Comment by blerner** [comment]
Note: we *don't* have the `Foo` name readily available from the `foo` function, so it's not easy to mention `Foo` directly in any error message about `foo`.

**Comment by jpolitz** [comment]
I think the boolean function `Foo` is just a silly thing to have around.  Maybe it's simply time for it to go.  Pyret _already_ binds `is-Foo` along with `Foo`, and the `Foo` thing is just a holdover from the way annotations used to work.

Then it makes a little more sense to augment the `unbound-id` error to check if the identifier that's unbound is actually bound as something else (like a type), and report a special error statically.

I'm fine with there being metadata on constructor functions that is only used for errors; in general there are lots of kinds of information that are only available when errors happen, and I don't see an issue with it.

**Comment by blerner** [comment]
I'd love for `Foo`-the-predicate to disappear, though I suspect that's going to be _very_ tricky to pull off (it'll require changing the interpretation of `cases(Foo)`, then bootstrapping, then removing `Foo`-the-predicate, then hoping we caught everything, I think).  Fixing up `unbound-id` will probably be easier, since the type-environment is already threaded through...but it's a hack job (everything about `BindingInfo` was a hack that should be expunged and replaced with actual static module information).  

At any rate, fixing the error message for `Foo` is a *lot* more involved than fixing it for `foo`, and more invasive work than I think is likely to land by July 1.  @schanzer is it ok if we just manage the message I described above, for `foo.x`, for now?

**Comment by jpolitz** [comment]
Huh?  The predicate isn't used in compiling `cases`.  I know this because that's an annotation position, and I can write

```
cases(Number) empty: end
```

and get an error message that `empty` isn't a `Number`.

Desugaring just inserts a let-binding with the annotation:

https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/desugar-post-tc.arr#L16

So I don't think that predicate is used at _all_ relative to `cases`.  Am I totally confused?

**Comment by blerner** [comment]
Exactly -- then that annotation on the let binding flows all the way through to `checkAnn` in the runtime.  So `Number`-the-predicate gets used, as would `Foo`-the-predicate.  If `Foo` weren't in scope as a value, then `cases` would wig out about an unbound name in that position.  It's also why you can write `cases(Any%(myRefinement))` and have it compile "correctly" with respect to the annotation, even though it makes no sense at all as a cases discriminator.

**Comment by jpolitz** [comment]
I am so confused.  There are two versions of `Foo` bound currently: an annotation and a value.

I was proposing removing the value binding, and saying that nothing we use currently relies on the value binding.  That matches the value that @schanzer's program was using to do a `.x` in expression position.

I would not remove the annotation binding, so cases (and other things that use `Foo` as an annotation, like `x :: Foo`) would still work.

**Comment by schanzer** [comment]
@blerner I'm assuming you mean this?
"The field lookup expression attempted to lookup a field on a constructor for `foo`, rather than a constructed `foo` object."

It's very wordy, and uses "lookup" and "constructor" as both an adjective and a verb. I had to read it twice to really parse it. It also fails to use all of the relevant information - is that because we don't have access to the fieldname? If we have it, I'd go with:

"Attempted to lookup a field `x` on a constructor (`foo`), but field lookups can only be performed on objects."

**Comment by blerner** [comment]
We do have the field name available for use, but I don't see how your proposed message is much better -- it also uses "lookup" as a noun and a verb, and the field name itself is a red herring in this message, since there's nothing you can do knowing that field name that would resolve the error.

Anyway, the wording itself is less critical than having the infrastructure in place to distinguish this message from the other field-lookup-on-non-object cases.

**Comment by schanzer** [comment]
You're right about the noun/verb use - I misspoke earlier about why your proposed wording is hard for me.

I think my first concern is really about the phrase "The field lookup expression attempted to lookup a field". There's a lot of redundancy there, and it almost feels circular. It's sort of like saying "a plumbus chubler attempted to chuble a plumbus". By referencing the field name and the constructor, it gives context clues as to what a field lookup is, and on what it was attempted.

This is echoed (to a lesser degree) in my other concern about the second phrase, "a constructor for foo, rather than a constructed foo object". The second one requires the user to tease out the difference between a "constructor for foo" and a "constructed foo".

**Comment by blerner** [comment]
But the field name is irrelevant and misleading here.  I agree that to someone who doesn't know what a field lookup is, the wording I currently have is unhelpful.  But targeting their limited and novice attention at _the one thing that won't fix the problem_ seems like a misguided idea.  ("Pyret is telling me that `x` didn't work, I guess I'd better try `y`.")  Focus the message on the `foo`.

I agree that "constructor for foo" and "constructed foo object" is a subtle difference in wording.  If you can come up with more blatant descriptions, I'll use them.

**Comment by schanzer** [comment]
`x` is not irrelevant - it explains which part of the offending syntax is the "field" part of a "field lookup". And yes, if a student changes it to `y` then they'll quickly realize that the problem isn't the field. I view that as a useful learning progression! If someone wasn't sure what `a.b` meant, I'd explain it as "trying to look up the field b from the object a" -- echoing this phrasing in the error message is an absolute win here. Is there a different explanation you'd give?

As for a better wording that addresses the constructor/constructed issue, my most recent proposal does this by only using the construct- root on the constructor:
"Attempted to lookup a field `x` on a constructor (foo), but field lookups can only be performed on objects."

This thread is getting long, which makes me think a short phone call might be more efficient. Let me know if you think that's worthwhile.

**Comment by blerner** [comment]
I clearly disagree with the premise -- I don't see how a student would wind up writing `foo.x` if they've never heard of fields before from somewhere, since periods aren't used in Pyret syntax anywhere else, and from a language perspective I don't much like the wording above's insinuation that "constructors" are somehow different from functions or other values in the language -- but I also don't care enough about the wording of this error to continue arguing.  I'll change it to your wording above, and if anyone else chimes in, they can feel free to edit the wording again.

**Comment by blerner** [comment]
In https://github.com/brownplt/pyret-lang/commit/aa3ae80f01a4593177628bb007fea9cc61b9955d
