### ISSUE TITLE
triangle chopping off bottom edge in outline mode

### ISSUE THREAD

**Issue by kfisler** [brownplt/code.pyret.org#89]
I just tried triangle(40, "outline", "red") and got a "triangle" without the bottom edge visible.  I can reproduce this with various sizes.  Happens whether I put the code in the interactions or definitions window.

Not sure whether this is a CPO issue or pyret-lang.

**Comment by blerner** [comment]
Probably related: https://github.com/brownplt/pyret-lang/issues/670 and https://github.com/brownplt/pyret-lang/issues/637.

**Comment by schanzer** [comment]
Does wescheme exhibit the same behavior? For you? If so, in what browser/operating system?

**Comment by kfisler** [comment]
WeScheme does NOT exhibit this behavior.  Outline triangles render just fine.  I'm in Chrome on OSX.

**Comment by jpolitz** [comment]
Just to note:  The actual fix for this issue was nothing sophisticated – just a minor edit to the image library about rounding widths and heights (literally adding `Math.round` in the `getWidth` and `getHeight` functions).  The DOM wrapper was one pixel too small because browsers take the floor by default.  Will push with other image merges coming soon.
